In [5]:
import pandas as pd
import numpy as np
from IPython.core.display import display, HTML
display (HTML('<h1 align="left">COVID-19 Cases in US</h1><h2>Total Cases: <font color="red">212,821</font></h2>'))
df = pd.read_csv('covid-19.csv')
dfnew = df.groupby(['State'])['Confirmed Cases'].sum().reset_index()
dfnew.sort_values(by ='Confirmed Cases' , ascending=False)
dfnew.style.hide_index()

In [4]:
Total = dfnew['Confirmed Cases'].sum()
display (HTML('<p>Total Cases in US:</p>')) 
Total
# I don't know how to add "total" column to the
# main table and make it look nice. So I calculated
# "total" here and added html to the table above

212821